#!/usr/bin/python3

import amulet
import requests
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment()
        self.port = 8123

        self.d.add('postgresql')
        self.d.add('odoo')
        self.d.configure('odoo', {'port': self.port})
        self.d.relate('odoo:db', 'postgresql:db-admin')
        self.d.expose('odoo')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['odoo'][0]

    def test_service(self):
        '''Tests Odoo is alive, jsonrpc requires at least Odoo 8.0'''

        url = 'http://{}:{}'.format(self.unit.info['public-address'],
                                    self.port)
        params = {
            'service': 'common',
            'method': 'version',
            'args': {},
        }

        response = requests.get(url, json={'params': params})
        self.assertEqual(response.status_code, 200)

        result = response.json()['result']
        self.assertIn('server_version_info', result)
        self.assertIsInstance(result['server_version_info'], list)

        
if __name__ == '__main__':
    unittest.main()
